wsi_SOURCES =              \
    physicaldisplay.cpp \
    drm/drmdisplay.cpp \
    drm/drmbuffer.cpp \
    drm/drmplane.cpp \
    drm/drmdisplaymanager.cpp \
    drm/drmscopedtypes.cpp \
    drm/hwclock.cpp \
	$(NULL)
